# Generated by Django 3.2.18 on 2023-03-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
