# Generated by Django 3.2.18 on 2023-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('category_brand', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_sales', models.IntegerField(blank=True, default=400, null=True)),
            ],
            options={
                'unique_together': {('name', 'price', 'category')},
            },
        ),
    ]
