# Generated by Django 3.2.18 on 2023-04-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
