# Generated by Django 3.2.18 on 2023-04-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='field_name',
            new_name='product_img',
        ),
    ]
