# Generated by Django 3.2.18 on 2023-04-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Customer',
        ),
    ]
