# Generated by Django 3.2.18 on 2023-04-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230403_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
