# Generated by Django 3.2.18 on 2023-04-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
