# Generated by Django 3.2.18 on 2023-04-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_order_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
