# Generated by Django 3.2.18 on 2023-04-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
