# Generated by Django 3.2.18 on 2023-04-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
