# Generated by Django 3.2.18 on 2023-04-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='placed_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
