# Generated by Django 3.2.18 on 2023-04-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
