# Generated by Django 3.2.18 on 2023-04-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderitem',
        ),
    ]
